### ISSUE TITLE
Issue with router class 

### ISSUE THREAD

**Issue by zackzulg** [vert-x3/issues#109]
Good morning, 

I just begin with Vertx in the official documentation and I would like to test routes in eclipse but I get some error from the code.
First error when I change router.route to Router route : 
> Cannot make a static reference to the non-static method route(String) from the type Router

Second error when I let router.route : 

> router cannot be resolved.

Tirth one when I add to my code : 

                HttpServer server = vertx.createHttpServer();
		Router router = Router.router(vertx);

> The type io.vertx.rxjava.core.Vertx cannot be resolved. It is indirectly referenced from required .class files

 Here is my code :
 
         import io.vertx.core.*;
         import io.vertx.rxjava.ext.web.*;
         import io.vertx.core.http.HttpHeaders;

         public class Test extends AbstractVerticle{
	
	@Override
	public void start() throws Exception {
		
		Route route1 = Router.route("localhost:8080/Test1/").handler(routingContext -> {

			  HttpServerResponse response = routingContext.response();
			  response.write("Test1 \n");
			  
			  routingContext.vertx().setTimer(5000, tid ->  routingContext.next());
			});

			Route route2 = router.route("localhost:8080/Test2/").handler(routingContext -> {

			  HttpServerResponse response = routingContext.response();
			  response.write("Test2 \n");
			  
			  routingContext.vertx().setTimer(5000, tid ->  routingContext.next());
			});

**Comment by sczyh30** [comment]
Hello, 
First the `Vertx` instance in the `AbstractVerticle` class refers to `io.vertx.core.Vertx`, not `io.vertx.rxjava.core.Vertx`. So you are supposed to import `io.vertx.ext.web.Router` rather than `io.vertx.rxjava.ext.web.Router`, or it won't match.
Second, the `Route#route` method is not a static method so first you need to create a Router instance:
```java
Router router = Router.router(vertx);
```
And then invoke the route method:
```java
router.route("/Test1").handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response.setChunked(true);
            response.write("Test1 \n");

            routingContext.vertx().setTimer(1000, tid ->  routingContext.next());
        });
```
Notice that the `route` method **does not** accept the absolute URL so you needn't pass the absolute URL. Directly pass the `/Test1` URL path and the host and port can be configured when createHttpServer.
Another notice is that if you want to write bytes directly to response, you should add `response.setChunked(true)` or an exception would be thrown:
```java
java.lang.IllegalStateException: You must set the Content-Length header to be the total size of the message body BEFORE sending any data if you are not using HTTP chunked encoding.
```
By now you have established a simple route, so next step is create a HttpServer:
```java
vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(8080, "127.0.0.1", res -> {
                    if (res.failed())
                        res.cause().printStackTrace();
                });
```
Well, the port and host can be passed to the `listen` method.
So this is the changed correct code:
```java
import io.vertx.core.AbstractVerticle;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.ext.web.Router;

public class TestVerticle extends AbstractVerticle {

    @Override
    public void start(Future<Void> startFuture) throws Exception {
        Router router = Router.router(vertx);

        router.route("/Test1").handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response.setChunked(true);
            response.write("Test1 \n");

            routingContext.vertx().setTimer(1000, tid ->  routingContext.next());
        });

        vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(8080, "127.0.0.1", res -> {
                    if (res.succeeded())
                        startFuture.complete();
                    else
                        startFuture.fail(res.cause());
                });
    }
}
```
Run this by deploy the verticle:
```java
public class Application {

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        TestVerticle verticle = new TestVerticle();

        vertx.deployVerticle(verticle, res -> {
            if (res.failed())
                res.cause().printStackTrace();
        });
    }
}
```
So this is only a simple example. And if you want to build a RESTful Service, this article might help: [Some Rest with Vert.x](http://vertx.io/blog/some-rest-with-vert-x/)

And here is my example of a RESTful Service using Vert.x Web, which may also help:[https://github.com/sczyh30/todo-backend-vert.x](https://github.com/sczyh30/todo-backend-vert.x)

I hope these can help you :)

**Comment by zackzulg** [comment]
Good morning,
Thank you  sczyh30, yes your explications help me to get more infos about Vert.x.
For my errors I didn't import the right classes, so now everything works fine.
Regards.

**Comment by cescoffier** [comment]
Issues reported as invalid by the reporter.
