### ISSUE TITLE
provide a kubernetes/DNS discovery plugin so that vertx containers (and HazelCast nodes) can discover each other when running inside Kubernetes/OpenShift/Atomic

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues#13]
Moved from https://bugs.eclipse.org/bugs/show_bug.cgi?id=470876

Originally posted by @jstrachan.

Right now manually wiring up HazelCast nodes is a PITA and multicast doesn't typically work in docker / kubernetes / clouds.

Here's an example of how to discover nodes using DNS when running on OpenShift or kubernetes with DNS enabled:
https://jimmidyson.github.io/clustering-on-kubernetes--openshift3-using-dns/

Or you could use the Kubernetes REST API (which also requires secrets so its a bit harder to use)
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/cassandra/java/src/io/k8s/cassandra/KubernetesSeedProvider.java#L105

So the DNS option - using an environment variable of the name to lookup; vertx should be able to auto-disover the nodes it needs to connect to for Vertx / Hazelcast etc

e.g.

$ dig @localhost elasticsearch-cluster.default.local. +short
172.17.0.13
172.17.0.10
172.17.0.11

The nice thing about the DNS approach is vertx has DNS support already and there'd be no code dependency on kubernetes then!

**Comment by purplefox** [comment]
Some more information on the Hazlecast proposal for a discovery SPI: https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI

**Comment by purplefox** [comment]
I think whatever we do here, it would be good to make it reusable by other cluster managers, e.g. jgroups, zookeeper etc not just HZ specific.

**Comment by w0mbat** [comment]
Why would one need DNS to discover nodes inside a Kubernetes cluster? If I understood @kelseyhightower at dockercon last week correctly, using DNS is not the preferred way.

We are heavily using Vert.x, Docker and Kubernetes and don´t have any problems at all discovering the nodes. We are using Weave to enable multicasting, it would also be possible via Project Calico.
Another easy way would be to do a lookup on the ips of the kubernetes services, that do a dynamic proxying to the vertx pods.

**Comment by jstrachan** [comment]
To create a cluster of Hazelcast, ZooKeeper, JGroups or other technologies like Cassandra or MongoDB - the server nodes need to discover each other to form a server side mesh. In Kubernetes there's 2 main standard ways using OOTB kubernetes; using the REST API or using DNS. For background of [how to use a simple DNS query see this article](https://jimmidyson.github.io/clustering-on-kubernetes--openshift3-using-dns/).

If you have a Kubernetes installation with a custom network plugin like Weave to enable multicast; then this issue isn't for you - just use the current multicast discovery in things like Hazelcast or JGroups.

However out of the box Kubernetes, Atomic, OpenShift, CoreOS, OpenStack and Google's GKE does not have multicast enabled.

So if you don't have multicast enabled, it'd be great for whatever cluster engine in vertx (Hazelcast / ZK / JGroups) to discover the server nodes automatically without the user having to install Weave or hack IP addresses by hand. On Kubernetes that means either the REST API or DNS.

> Another easy way would be to do a lookup on the ips of the kubernetes services, that do a dynamic 
> proxying to the vertx pods.

This issue is all about finding the IP addresses of the pods ;). There are 2 main ways to do this - REST and DNS.

Note that if you just wish to invoke a service (invoke some pod from a pool over a network port) using load balancing then Vertx can do that trivially do that by  [just using 2 environment variables](http://fabric8.io/guide/services.html#discovering-services-from-your-application).

But to find all the Hazelcast nodes or ZK server nodes you need to just find all the IP addresses of the pods implementing the services. This is available via the `endpoints` REST API on a service in kubernetes. So you can totally find this via a REST call. The issue is to make REST calls on the k8s REST API - due to security - you need to then give each vertx node a token / login/pwd; or typically add secrets & service accounts so that it can use the REST API then write Java code to use the REST API. We've a [nice library for doing that in the fabric8 project](https://github.com/fabric8io/fabric8/tree/master/components/kubernetes-api). So its totally possible - and we do it quite a bit inside the [fabric8](http://fabric8.io/) project.

Though the simplest thing to find the list of IP addresses for the pods implementing a service - in terms of the vertx end user - is actually to make a DNS query. Then there's no need for a custom token/secret/service account configured into of your vertx apps. Just via a small bit of Java DNS code the discovery would just work OOTB (and vertx already has DNS java code).

i.e. the best way to make cluster discovery just work for Hazelcast/ZK/JGroups, in all Kubernetes installations OOTB with minimal impact on end user vertx applications is via DNS. Using the REST API could be another plugin; but as I've explained; its sub-optimal as its more complex to configure (due to security) but is pretty easy to do as well. I'd be happy with either approach really; but DNS is gonna be easier for folks to use

**Comment by cescoffier** [comment]
Should we postponed this feature to 3.2.0 ?

**Comment by cescoffier** [comment]
Postponed to 3.3.0.

**Comment by cescoffier** [comment]
It will be very easy with the new Hazelcast, as they support Kubernates discovery.

**Comment by purplefox** [comment]
It's done here https://github.com/purplefox/ipaas-quickstarts/tree/master/quickstart/vertx :)

**Comment by purplefox** [comment]
https://github.com/fabric8io/ipaas-quickstarts/pull/1098

**Comment by purplefox** [comment]
Yep, it needs HZ upgrading to 3.6+ and also HZ team needs to release a new version of the plugin.

**Comment by niqhil** [comment]
http://blog.hazelcast.com/openshift/

**Comment by vietj** [comment]
@tsegismont what shall we do with this issue ?

**Comment by tsegismont** [comment]
@vietj Hazelcast has a discovery SPI since 3.6. Users can include hazelcast-kubernetes jar in their project and configure as documented here https://github.com/hazelcast/hazelcast-kubernetes/blob/master/README.adoc

**Comment by vietj** [comment]
thanks for closing it!

**Comment by vietj** [comment]
should we link that in the current Vert.x HZ doc ?

**Comment by tsegismont** [comment]
I don't think this is mandatory. There are plenty of discovery plugins
which could be documented as well. If someone contributes it I would
certainly consider merging though.

2018-01-11 15:54 GMT+01:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
I think we should at least add a note to use specific discovery plugin in such env

**Comment by cescoffier** [comment]
There is an official HZ support for kubernetes. The discovery implementation we did has been removed in favor of the official one.

**Comment by vietj** [comment]
I just means that in such managed env, the doc could say to look at the related plugin for this env
