### ISSUE TITLE
Separate api from impl

### ISSUE THREAD

**Issue by gchauvet** [vert-x3/issues#176]
It would be nice to split API from implementation : 
vert-api <<used by>> vertx-core

**Comment by apatrida** [comment]
How useful is this really?

**Comment by gchauvet** [comment]
IMO, this is an unavoidable step before exposing Vertx as a real OSGi bundle

**Comment by vietj** [comment]
given there is a single implementation of `Vertx` and no alternate implementation, what does it buy to have such separation ?

**Comment by aschrijver** [comment]
You could selectively use interfaces in projects that can be used stand-alone or with Vertx without  pushing the whole impl and most or some of its transitive dependencies. Like with `JsonObject` in another thread.

**Comment by vietj** [comment]
@aschrijver can you give a precise example of what would be possible that is _not_ possible now ?

**Comment by aschrijver** [comment]
Well I would first like to state that I am not the requester of the feature.
We had an earlier discussion on JsonObject being a nice and handy thing also suitable for non-vertx projects. But unsuitable because you don't ship whole core with it. There may be a whole lot of other such examples like maybe Future etc.

Another rationale for this feature could be further modularization of core. I don't know how valuable this is and there are many ways to do it, but its something to consider at least.

I read an issue today stating that parts of Apache Ignite overlap vertx default classes but are better, more stable. Could it be separated out? Dunno.. :)

**Comment by pmlopes** [comment]
With vert.x 4.0.0 OSGi metadata will not be included anymore with the distributed jars.

For JSON we now allow custom CODECs and have support out of the box for JacksonCore or Jackson Databind
