### ISSUE TITLE
Integrate with Ignite, drop redundant features

### ISSUE THREAD

**Issue by apatrida** [vert-x3/issues#177]
Apache Ignite has strong implementations of many useful distributed features.  Basically replacing Hazelcast and parts of Vert.x.  Consider adopting it and dropping the redundant parts that were previously separately implemented.   I've found Ignite to be more stable and functional than equivalents in Vert.x.  It brings much more to the table, and in a modernized and easy to use way.

**Comment by apatrida** [comment]
somehow I missed vertx-ignite module coming around.  Ignore me

**Comment by aschrijver** [comment]
@apatrida Interesting! This could be a good topic for a blog post comparing pro's/cons of Hazelcast vs. Iginite and how it overlaps with current Vert.x stuff.

I am using Hazelcast right now, but mostly because its the best supported, longest around, and the default. Have looked at Zookeeper for its service discovery features before `vertx-service-discovery` came about, but decided against using it. Personally I would need some convincing, before switching to the 'latest and greatest' :wink:
