### ISSUE TITLE
Add OAuth2 Implicit Flow

### ISSUE THREAD

**Issue by faeron** [vert-x3/issues#179]
I just came across the vertx-oauth2 package and recognized that the implicit flow is missing. Are there any plans on adding it to the package aswell? Or are there reasons why this doesn't make sense?

**Comment by pmlopes** [comment]
The implicit flow is designed for apps running on the client, when the other flows were implemented I did not thought people would be embedding vert.x but it is a valid good point.

**Comment by pmlopes** [comment]
@skullcrasher I'm reading again the spec and from what I understand the implicit flow is a flow to be used by browser based applications or mobile applications. Since the entire source code is available to the browser, they cannot maintain the confidentiality of their client secret, so the secret is not used in this case.

If the application is running on a browser I'm asking myself what is the point of implementing this flow on the server? I can start the flow from javascript on my html and retrieve the token also on my html. My server has no need to know anything about it.

The only case I can imagine one would want this implemented server side was to collect the token and associate to the session e.g.:

JavaScript calls oauth2 provider with redirect to custom handler that parses the response hash and adds to the session, finally returns the static html file. What is dangerous here is that since the server does not initiate the request the calls to the callback can be forged easily which leads to a security issue.

Other thing is that for example on iOS the implicit flow can use intra-app communication for example you can authenticate with facebook with `fbauth2://token?...` which redirects to `fb000000://...#token` this would never reach our server since the redirect protocol is not http/https.

I'm thinking that this should not be implemented server side.

**Comment by pmlopes** [comment]
Reference: https://tools.ietf.org/html/draft-ietf-oauth-v2-15#section-4.2
I'll mark this invalid, please reopen if you disagree.
