### ISSUE TITLE
Making coming release compatible with RxJava2

### ISSUE THREAD

**Issue by SercanKaraoglu** [vert-x3/issues#189]
RxJava has just come out with one of the biggest release candidate which includes bug fixes cleanups and improvments they changed whole api with this it is now closer to Java 8 and I would like vertx to be compatible with coming releases of RxJava

**Comment by EmadAlblueshi** [comment]
:+1:

**Comment by marcinczeczko** [comment]
+1

**Comment by KrzysztofKowalczyk** [comment]
When creating RxJava 2 version maybe it is possible to make it easier to use the Rx API and also make it more explicit. Take for example the Q&A, were both question and answer is wrong:
http://stackoverflow.com/questions/35494828/how-to-end-chained-http-requests-in-rxjava-vert-x 
- a typical problem with calling end after subscription 
- never actually calling end() 
- buffers are not merged

Thus I see some possible improvements in rx2 version:
-  use Single were appropriate to make it explicit when only one element is expected (response) and Observable when many (Buffers, eventbus, server)
- provide more methods like RxHelper.get. RoutingContext has getBodyAsJson, it would be nice to have something like that on the client. Doing simple things with client should be simple

Other than that, mixing vertx-web and rxverxt does not feel right, some rxified routing maybe? Once handler can consume observable writing server handlers with client calls is quite nice looking.

Not sure if deciding do we have Single or Observable would be possible currently with code generation approach. To be honest, I never liked it and prefer static methods over generated classes. At the moment there are some methods in rx RxHelper which do not exist in RxHelper. Having static method for normal types would work well with languages that have support for extensions, like groovy, so it could limit the need for additional rx groovy extensions.

**Comment by vietj** [comment]
@KrzysztofKowalczyk 

for the next version 3.4.0 we plan to have an `HttpRequestClientBuilder` whose goal is to make easier to create http client requests, this is currently a WIP you can check either in GitHub or in the dev group : https://groups.google.com/d/topic/vertx-dev/HN0tJs-BZqk/discussion

Concerning the API it should actually use `Single`, `Observable` and also `Flowable`.

The RxGroovy version uses extension methods.

I think some people tend to like the code generated version as it makes easier to chain operations when there are many vertx types involed, but I think it's a matter of taste. You can still uses the `RxHelper` version with the original Vert.x API.

**Comment by vietj** [comment]
in case you want to look at the RxJava2 experiments https://github.com/vert-x3/vertx-rx/tree/rxjava2

**Comment by KrzysztofKowalczyk** [comment]
My usage of rx in might differ significantly from others. I don't use any of vertx generated classes nor do I use toObservable. Maybe it will be of some use if I just try to explain it. I understand it would be harder to support everything vertx does in a similar way.
I build rest microservice that calls many other services. Hence I optimise how easy it is to do a call, retry on failure, have exponential backoff and return what I received. I always want a full body in both client and server calls (with a size limit). I use only schedulers from vertx rxjava and created some rx glue for client and server.

For the client I have something like that :

```
    public Single<JsonObject> req(HttpMethod method, String url, Optional<JsonObject> body) {
        HttpClientRequest request = client.request(method, url);
        request.headers().addAll(headers);

        return Single.<Buffer>create(s -> {
            request.handler(response -> {
                response.bodyHandler(s::onSuccess);
                response.exceptionHandler(s::onError);
            });

            request.exceptionHandler(s::onError);

            if (body.isPresent()) {
                request.end(body.get().toString());
            } else {
                request.end();
            }
        })
        .map(Buffer::toJsonObject);
    }
```

So it is like RxHelper.get, just going further as I can in my case.
This is simplified, as original have more exception handling, headers, unsubscribe, content type, different handling of 5xx, 4xx etc. There is no need in my case to make it generic, so I always download the whole body. Then decide with a strategy do I want to fail because of wrong status code ((resp, body) -> rest.statusCode > 200  ? throw badResponse(resp, body) ).

Then for the server I use vertx-web plus 2 function wrappers:

```
    public static <U> Handler<RoutingContext> end(Function<RoutingContext, Single<U>> handler) {
        return rc ->
            handler.apply(rc)
                .subscribe(
                    result -> handleSuccess(rc, result), // renders result if json, model etc
                    rc::fail
                );
    }

    public static <U> Handler<RoutingContext> next(Function<RoutingContext, Single<U>> handler) {
        return rc ->
            handler.apply(rc)
                .subscribe(
                    ignore -> rc.next(),
                    rc::fail
                );
    }
```

Those takes functions that return single and execute them. First will try to render the value that single returns, second will continue after single returns. Thus it kind of flat maps my single so it can act as a handler. Hence instead of needing to subscribe to single whenever I use then in handler, I just return a Single with value I want to render and I'm done.

This makes the client pretty easy to use in practice inside of a handler

```
// validate id, go to next handler if ok
router.get("/").handler(
  next(rc -> 
    client.req(GET, "/exists/"+rc.getParam("id"), empty()))
   .doOnSuccess(resp -> if(!resp.getBoolean("valid")) throw invalid(resp.getString("id")))
);
// respond with value I got
router.get("/").handler(end(rc -> client.req(GET, "/hello", empty())));
```

I can still use all good parts from Router, put stuff in RoutingContext and have the request body there. But my "handlers" understand Single so I don't have to break out of Single chain when doing async calls. 

Below a parallel call to couchbase (which expose rx api wraped in a dao to return single<json>) and some external service:

```
router.get("/add").handler(end(rc -> 
  Single.zip(couchbaseDao.getA(), client.req(GET, "B", empty()),
    (a, b) -> new JsonObject().put("value", a.getInteger("value") + b.getInteger("value")))
)
```

I don't support backpressure in any way, but it turned out simpler and cleaner than my previous approach where I tried to create Observable<RoutingContext> per route.

**Comment by dano** [comment]
I was thinking it might be worthwhile to switch to RxJava2 when I convert my project from using xyzObservable methods to RxXyz methods, but it seems the RxJava2 integration isn't quite ready. What's the status of the rxjava2 branch at this point?

**Comment by vietj** [comment]
RxJava2 should be released in Vert.x 3.5, this branch https://github.com/vert-x3/vertx-rx/tree/rxjava2 contains the development of the feature and it should be usable as preview as it supports core api generation and verticle deployment

**Comment by vietj** [comment]
See https://github.com/vert-x3/vertx-rx/issues/95 with all the infos

**Comment by pmlopes** [comment]
Rx2 is already implemented.
