### ISSUE TITLE
Handle SLF4J issue

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#239]
during the release of the 3.4.0.Beta1 we noticed that in the vertx CLI version now is printed:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

this is due to this commit in  https://github.com/netty/netty/commit/71efb0b39e4410001abb9d96c6a87316a567c16f

Short explanation: when Netty configured SLF4J logging it was replacing for the duration of the creation System.err, so this does not appear on the stderr. Somebody complained and now it is removed.

In the CLI distrib we do have SLF4J API but no implementation hence now I could see this on the console.

To solve this, we removed SLF4J from the CLI distrib with some exclusions, but this does not well because Apache Shiro is using SLF4J natively which means that in reality there will be a dependency that uses SLF4J directly…

So this raises a few interesting points / questions:

- how do we handle SLF4J dependency
- when Netty configure its default logging, it will always assume SLF4J is used even if there is not implementation jar, which means that the user should configure Netty logging to the right logger if he wants to get the right logging or configure SFL4J to redirect to his current logger. Consequently Vert.x and Netty could use 2 different loggers by default.

**Comment by vietj** [comment]
Handling SLF4J could be:

- dependencies with an optional SLF4J dependency should have SLF4J excluded or in provided scope (for instance Thymeleaf)
- dependencies with a mandatory SLF4J dependency should declare SLF4J

The Vert.x Launcher class when it check if SFL4J is visible in its classloader and the class is not initialized, basically does the same than Netty. This is done in the `main(String[] args)` and not in a static block.

**Comment by vietj** [comment]
About Netty logging, there are a few facts:

- configuring Vert.x logging (by settings the `vertx.logger-delegate-factory-class-name`) will configure Vert.x logging but Netty logging might go somewhere else. In addition Netty logging is not configurable via system properties and it a fallback mechanism that can be overridden programmatically. So in Vert.x CLI distribution it might be suitable that this configuration happens.
- at the same time Vert.x should prevent itself from doing magic...

So perhaps that Netty logging should be configured in the `Launcher` like described in the previous comment.

In addition all of that would be documented, so the user knows exactly what to expect for in the various situations.

**Comment by tsegismont** [comment]
If we customize Logging in the launcher then it should be possible for the
user to override the default behavior.

2017-02-09 21:34 GMT+01:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
2017-02-09 21:29 GMT+01:00 Julien Viet <notifications@github.com>:

> Handling SLF4J could be:
>
>    - dependencies with an optional SLF4J dependency should have SLF4J
>    excluded or in provided scope (for instance Thymeleaf)
>
>
Shouldn't it be optional rather than provided?


>
>    - dependencies with a mandatory SLF4J dependency should declare SLF4J
>
>
+1

**Comment by vietj** [comment]
@tsegismont optional/provided : either way :-)

**Comment by cescoffier** [comment]
I'm not sure it's going to work with "optional", as using optional when dealing with transitive dependencies can easily get wrong. 

Actually, I'm still wondering what can we do on this issue. I also tried to avoid SLF4J, and mark it as provided everywhere - but I didn't take into account the Netty case. 

If we provide a vert.x stack without SLF4J-API and binding, some of the components of the stacks won't work. So we should probably not include them by default (and add a comment to indicate to the user to add slf4j). 

In a regular Maven / Gradle / SBT project, there is a good chance that SLF4J is part of the dependency tree. So, we end up with SLF4J in the classpath / fat-jar. If we only have the API, we would have the no-binding message. However, netty will use SLF4J without binding. So we should extend the doc to explain how to avoid this. Hiding the message would also remove the hint to the user that someone is using SLF4J without binding. 

I was thinking that we could discover this case and delegate to the Vert.x logger, but because of the structure of SLF4J (and its binding mechanism) it cannot be done at runtime.

**Comment by greggwon** [comment]
I would prefer the use of java.util.logging since it is built into Java and works quite readily to provide handler implementations to goto whatever destination you need.  It has been around for quite some time, and removing the use of SLFJ from all code on the internet would ultimately be the best approach so that there is a single solution that is accessible to all parts of any application.   The wide variability in the use of logging packages just points at that fact that there should be one, and java.util.logging, is already in the JDK, so why not use it?

**Comment by pmlopes** [comment]
Logging is no longer a concern of core, users are advised to add a logger to the classpath which will solve this issue.
