### ISSUE TITLE
Integrate Router into HttpServer

### ISSUE THREAD

**Issue by amorozow42** [vert-x3/issues#255]
In the preface for Vert.x Web is said:

"It’s the successor to Yoke in Vert.x 2.x, and takes inspiration from projects such as Express in the Node.js world and Sinatra in the Ruby world.".

Express is very convenient tool because we can use it like this:

```
var express = require('express')
var app = express()

app.get('/', function (req, res) {
  res.send('Hello World!')
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
```

So I was surprised that in Vert.x I can define routes only that way:

```
Router router = Router.router(vertx);
router.get("/some/path/").handler(routingContext -> {
  routingContext.response().putHeader("content-type", "text/plain")
                           .end("Hello World from Vert.x-Web!");
});

vertx.createHttpServer().requestHandler(router::accept).listen(8080);
```

and can not do it the Express way:

```
vertx.createHttpServer().get("/some/path/", (req, res) -> {
  res.putHeader("content-type", "text/plain")
     .end("Hello World from Vert.x-Web!");
}).listen(8080);
```

Why we should always use this boilerplate code to set routing?
For example, I never need to separate routing from server, but must do it every time nevertheless.
I understand that such use cases can be sometimes, but it would be really nice to have default and convenient way.

**Comment by pmlopes** [comment]
express also has a different API if you want to use HTTPS or HTTP2 and in that case it becomes more like vertx-web. There are a couple of possible improvements such as make the router implement `Handler<HttpServerRequest>` so you can use it directly like:

```java
vertx.createHttpServer().requestHandler(
  Router.create().get("/some/path/").handler(ctx) -> {
    ctx.response()
      .putHeader("content-type", "text/plain")
      .end("Hello World from Vert.x-Web!");
  })
).listen(8080);
```

**Comment by amorozow42** [comment]
Router is absolutely excess object in this case.
It should be an inner part of server to support routing, but not be exposed outside.

**Comment by vietj** [comment]
@romero are you just saying that doing `Router.create()` is too complicated ?

**Comment by amorozow42** [comment]
@vietj Yes, I think it is redundant here and so code are looking more complicated then it could be.

**Comment by pmlopes** [comment]
@romero HttpServer (as with node.js) is purely an HttpServer, it has no knowledge of routing, this is an high level feature. For example, when dealing with high performance you might not want a Router since you probably will only a accept a specific type or request and will not need to perform pattern matching and all the helper features the router does.

Router is as in your example the (express) object from node where high level API's are built on top of HttpServer.

Sure you might argue that it could have a API like express, where the listen method would create an HttpServer for you, but what if you want more control? say HTTPS and the allowed cyphers, etc... or HTTP2? In this case we would end up replicating all the API in this class.

In node with express you will need something in these lines:

```js
var express = require('express')
var app = express()
var fs = require('fs');

var options = {
  key: fs.readFileSync('./localhost.key'),
  cert: fs.readFileSync('./localhost.crt')
};

require('http2').createServer(options, app).listen(8080);
```

As you can see it's not that different from what we do.

**Comment by amorozow42** [comment]
@pmlopes Ok, I understand your words.
Of course my initial question was about introducing some high level class with integrated routing, e.g. WebServer. And if you need more control you can use low level API.
In 99% of cases we don`t need high perfomance, so why should we always write this:

`server.requestHandler(router::accept);`
