### ISSUE TITLE
Render template without RoutingContext.

### ISSUE THREAD

**Issue by romnovi** [vert-x3/issues#310]
We have method:
TemplateEngine.render(RoutingContext context, String templateDirectory, String templateFileName, Handler<AsyncResult<Buffer>> handler)

Would be great have possibility for rendering without obligatory RoutingContext context

**Comment by tsegismont** [comment]
Why not use the raw template engine classes directly instead? Vert.x Web
template engine classes are designed to render pages from a Vert.x Web
routing context.

2017-11-21 15:38 GMT+01:00 Roman Novikov <notifications@github.com>:

**Comment by pmlopes** [comment]
@mystdeim I'm looking at this and thinking, we probably could create a render method with a `Map` as the source of the template variables, however, the context has already a map for you and that is where the variables are extracted from.

What would be the benefit of this since this API is used inside `web` there is always a context. I don't see the use case, but feel free to tell more about it.

**Comment by mllrmat** [comment]
@pmlopes I would like to render emails with templates. In this case I do not have a routingcontext, so it would be handy to use the templateengine

**Comment by castx1981** [comment]
I have exactly the same requirements as @mllrmat, to be more specifically, I would like to have a service running in backgroud to render emails with templates and send out, there is no RoutingContext involved in this case.

**Comment by tsegismont** [comment]
@pmlopes I asked @castx1981 to comment on this issue. It seems the use case is not isolated. How about looking into it for 3.6?

**Comment by pmlopes** [comment]
We can decouple the engines, however the base interface is on web so it always pulls it as a dependency, we could introduce a new interface just in common with map and deprecate the old one on 4.x?

**Comment by tsegismont** [comment]
Sounds good but what do you mean with "just in common"?

**Comment by pmlopes** [comment]
I mean recreate the interface from `vertx-web` in `vertx-web-common` otherwise if you just want to use a template engine you won't need to bring the full dependency tree from web to your project

**Comment by tsegismont** [comment]
@pmlopes I think I missed the news about this module. Can you briefly explain why it was created and why _BodyCodec_/_MultipartForm_ moved there? I'm trying to understand why the templ engines shouldn't be in their own module (not necessarily in a different repo)?

**Comment by pmlopes** [comment]
Those components never moved, they were there since day 1. The idea was that body codecs could be used by routing context to parse uploads and multipart could be shared with mail client to reduce duplication. This code was added with the web client. My idea to add the interface there would be to avoid having more modules.

**Comment by tsegismont** [comment]
Ok, thanks for the details. But why just the interface? If users need, for example, Vert.x Freemarker for implementation, they will still depend on `vertx-web`, won't they? I must be missing something obvious, sorry

**Comment by pmlopes** [comment]
I think the link can be broken. The `templ-` modules should depend on common instead of web, the original interface becomes deprecated and adapts the calls to the map version of the API. I haven't tested or checked it but I think it could be done.

**Comment by tsegismont** [comment]
OK, I just added this to the 3.6 milestone, can you please move it to vertx-web with Waffle?
