### ISSUE TITLE
How to refuse client subscribe?

### ISSUE THREAD

**Issue by wwhai** [vert-x3/issues#413]
Recently I face a problem:
I use vertex-mqtt design a server, now some client which want to subscribe topic will be deny.but I don't know how to do this function.
I hope in `endpoint.subscribeHandler`event can provide a interface can deny client who want to sub a special topic.
such this:
 List<MqttTopicSubscription> topicSubscriptions = subscribe.topicSubscriptions();
                            for (MqttTopicSubscription mqttTopicSubscription : topicSubscriptions) {
                                if (Arrays.asList(topics).contains(mqttTopicSubscription.topicName())){
//allow sub
                                }else {
//deny sub
                                }
                            }

**Comment by tsegismont** [comment]
@ppatierno do you know if this is possible?

**Comment by wwhai** [comment]
> @ppatierno do you know if this is possible?

I think this function is useful for a security mqtt service.
I hope you can enhance this interface future.

**Comment by ppatierno** [comment]
@wwhai @tsegismont it's already possible doing that as described by the MQTT protocol.
On the `MqttEndpoint` you have `subscribeAcknowledge` method in order to send the SUBACK to the connected client. You have to provide the list of granted QoSs. The `MqttQoS` enum has the three level of QoS and `FAILURE` to deny the subscription to the client.

**Comment by tsegismont** [comment]
@ppatierno thank you!

**Comment by ppatierno** [comment]
@tsegismont you are welcome!
