### ISSUE TITLE
start(Future<>) shoud be a start(Promise<>)

### ISSUE THREAD

**Issue by olivier-duval** [vert-x3/issues#494]
Hello,

I hard some hard time trying to make AbstractVerticle.start(Future<>) method work... because every attempt to complete the Future was failing. I had to track down the code to see that the argument is not really a Future<> but a Promise<>. After casting and using the right method, everything worked like a charm !

So I guess that there has been some changes in this implementation (using 3.8.1) but that it didn't completly propagate or that there was some backward-compatibility choice... Anyway, I think that it should be nice to have a method with the right argument type start(Promise<>) instead of start(Future<>) or added to the AbstractVerticle class

**Comment by tsegismont** [comment]
In 3.8.1, AbstractVerticle#start still takes a `Future`, not a `Promise`. So I'm not sure what you mean.

https://github.com/eclipse-vertx/vert.x/blob/3.8.1/src/main/java/io/vertx/core/AbstractVerticle.java

In master (4.0) it is actually a `Promise`.

https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/AbstractVerticle.java

I'm not sure which problem you had because both can be completed with the same method.
