### ISSUE TITLE
Guava upgrade to 30.1.1-jre

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#595]

**Comment by pmlopes** [comment]
Fixed by:

* https://github.com/vert-x3/vertx-grpc/pull/109
* https://github.com/vert-x3/vertx-stack/pull/130
* https://github.com/vert-x3/vertx-zookeeper/pull/123
* https://github.com/vert-x3/vertx-http-service-factory/pull/14
* https://github.com/vert-x3/vertx-service-discovery/pull/161
* https://github.com/vert-x3/vertx-health-check/pull/37
* https://github.com/vert-x3/vertx-maven-service-factory/pull/37
* https://github.com/vert-x3/vertx-config/pull/140
